package pokemonGame;
import java.util.List;
import java.io.Console;
import pokemonGame.db.*;
// For testing only: 
import pokemonGame.mons.*;

public class App {
    public static void main(String[] args) throws Exception {

        // IMPORTANT NOTE:
        // When creating a new Pokemon instance, create the Pokemon object first,
        // then call createDBPokemon to insert it into the database and get its generated ID,
        // then set that ID on the Pokemon object.  This is necessary because the Pokemon's ID is 
        // generated by the database upon insertion, so you won't have it until after you call createDBPokemon.

        // IMPORTANT NOTE 2: 
        // Do not couple in memory creation or modification of Pokemon objects with database operations.
        // For example, the addPokemonToTeam method in the Trainer class should only modify the 
        // in-memory team list and not perform any database operations.  Database operations should be 
        // handled separately in the App class by calling the appropriate methods in the PokemonCRUD
        //  and TeamCRUD classes after modifying the in-memory objects.

        // IMPORTANT NOTE 3:
        // When adding a Pokemon to a team, if the check fails for whether the team is full, 
        // do not add the Pokemon to the in-memory team list and do not call the method to add the 
        // Pokemon to the database team.  Instead, display a message to the user that their team is 
        // full and they cannot add more Pokemon. You must also check that the Pokemon is NOT in the 
        // pokemon_instances table if the team size check fails, to avoid having Pokemon in the database that are not on any team.


        // long discordID = 123456789012345678L; // Placeholder Discord ID
        // String discordUsername = "TestUserDiscord"; // Placeholder Discord username
        // String trainerName = "TestUser"; // Placeholder trainer name

        // createTrainer(trainerName, discordID, discordUsername);
        
        // PokemonCRUD pokemonCRUD = new PokemonCRUD();

        // Example of getting a specific Pokemon for the trainer by its instance ID (replace 1 with the actual instance ID you want to retrieve)
        /*
        int pokemonInstanceIdToRetrieve = 2; // Placeholder instance ID
        Pokemon retrievedPokemon = pokemonCRUD.getSpecificDBPokemonForTrainer(trainer, pokemonInstanceIdToRetrieve);
        if (retrievedPokemon != null) {
            System.out.println("Retrieved Pokemon: " + retrievedPokemon.getName() + " (" + retrievedPokemon.getSpecies() + ")");
        } else {
            System.out.println("No Pokemon found with instance ID: " + pokemonInstanceIdToRetrieve);
        }

        System.out.println(retrievedPokemon.getName() + " has this many hit points: " + retrievedPokemon.getCurrentHP());
        */

        // Example of updating a Pokemon's current HP and fainted status in the database
        /*
        if (retrievedPokemon != null) {
            retrievedPokemon.setCurrentHP(100); // Set current HP to 0 to indicate the Pokemon has fainted
            retrievedPokemon.setIsFainted(false); // Set isFainted to true to indicate the Pokemon has fainted
            boolean updateSuccess = pokemonCRUD.updateDBPokemon(retrievedPokemon);
            if (updateSuccess) {
                System.out.println("Pokemon '" + retrievedPokemon.getName() + "' (" + retrievedPokemon.getSpecies() + ") updated successfully in the database.");
            } else {
                System.out.println("Failed to update Pokemon '" + retrievedPokemon.getName() + "' (" + retrievedPokemon.getSpecies() + ") in the database.");
            }
        }
            

        // Retrieve the same Pokemon again to verify the update
        Pokemon updatedPokemon = pokemonCRUD.getSpecificDBPokemonForTrainer(trainer, pokemonInstanceIdToRetrieve);
        if (updatedPokemon != null) {
            System.out.println("After update, retrieved Pokemon: " + updatedPokemon.getName() + " (" + updatedPokemon.getSpecies() + "), Current HP: " + updatedPokemon.getCurrentHP() + ", Is Fainted: " + updatedPokemon.getIsFainted());
        } else {
            System.out.println("No Pokemon found with instance ID: " + pokemonInstanceIdToRetrieve);
        }   

        // Example of deleting a Pokemon from the database for a specific trainer
        // You must remove the pokemon from a team before deleting the database record to avoid foreign key constraint errors.
        // So first we will remove the Pokemon from the trainer's team, then delete the Pokemon from the database.
        int pokemonInstanceIdToDelete = 5; // Placeholder instance ID to delete
        Pokemon pokemonToDelete = pokemonCRUD.getSpecificDBPokemonForTrainer(trainer, pokemonInstanceIdToDelete);
        if (pokemonToDelete != null) {
            TeamCRUD teamCRUD = new TeamCRUD();
            boolean removedFromTeam = teamCRUD.removePokemonFromDBTeam(trainer.getDBId(), pokemonInstanceIdToDelete);
            if (removedFromTeam) {
                boolean deleteSuccess = pokemonCRUD.deleteDBPokemon(pokemonToDelete);
                if (deleteSuccess) {
                System.out.println("Pokemon '" + pokemonToDelete.getName() + "' (" + pokemonToDelete.getSpecies() + ") deleted successfully from the database.");
                } else {
                    System.out.println("Failed to delete Pokemon '" + pokemonToDelete.getName() + "' (" + pokemonToDelete.getSpecies() + ") from the database.");
                }
            } else {
                System.out.println("Failed to remove Pokemon '" + pokemonToDelete.getName() + "' (" + pokemonToDelete.getSpecies() + ") from the team.");
            }
        } else {
            System.out.println("No Pokemon found with instance ID: " + pokemonInstanceIdToDelete);
        }

        // Return entire team for the trainer from the database and display their names
        TeamCRUD teamCRUD = new TeamCRUD();
        List<Pokemon> teamFromDB = teamCRUD.getDBTeamForTrainer(trainer);
        System.out.println("Team retrieved from database for trainer " + trainer.getName() + ":");
        for (Pokemon p : teamFromDB) {
            System.out.println("- " + p.getName() + " (" + p.getSpecies() + ")");
        } 
        */

        // setup some test data for the bot to pull from the database and display when commands are used
        TrainerCRUD trainerCRUD = new TrainerCRUD();
        TeamCRUD teamCRUD = new TeamCRUD();
        PokemonCRUD pokemonCRUD = new PokemonCRUD();

        // Create a trainer 
        Trainer tallas = trainerCRUD.getTrainerByDiscordId(143562769591959552L);
        System.out.println("Trainer '" + tallas.getName() + "' retrieved successfully with Discord ID: " + tallas.getDiscordId() + ". Trainer DB ID is: " + tallas.getDBId());

        // Create a Pokemon for that trainer
        Pokemon tallasCharizard = new Charizard("Charizard");

        tallasCharizard.setTrainer(tallas);
        
        int charID = pokemonCRUD.createDBPokemon(tallasCharizard);
        
        
        tallas.addPokemonToTeam(tallasCharizard);
        teamCRUD.addPokemonToDBTeam(tallas.getDBId(), charID);

    
        // Create another trainer
        Trainer ian = trainerCRUD.getTrainerByDiscordId(1276823949652529204L);
        System.out.println("Trainer '" + ian.getName() + "' retrieved successfully with Discord ID: " + ian.getDiscordId() + ". Trainer DB ID is: " + ian.getDBId());


        Pokemon ianAlakazam = new Alakazam("Alakazam");
        ianAlakazam.setTrainer(ian);
        
        int alakazamID = pokemonCRUD.createDBPokemon(ianAlakazam);
        
        
        ian.addPokemonToTeam(ianAlakazam);
        teamCRUD.addPokemonToDBTeam(ian.getDBId(), alakazamID);

        Trainer cal = trainerCRUD.getTrainerByDiscordId(202621039392325632L);

        Pokemon calGengar = new Gengar("Gengar");
        calGengar.setTrainer(cal);
        int gengarID = pokemonCRUD.createDBPokemon(calGengar);
        cal.addPokemonToTeam(calGengar);
        teamCRUD.addPokemonToDBTeam(cal.getDBId(), gengarID);



    


        // Display the Team
        /*
        System.out.println("Your team:");
        for (Pokemon p : trainer.getTeam()) {
            if (p != null) {
                System.out.println("- " + p.getName());
            }
        }
        */


        //Display team stats
        /*
        System.out.println();
        System.out.println("Your team's stats:");
        for (Pokemon p : trainer.getTeam()) {
            if (p != null) {
                System.out.println(p.getName() + ": Level " + p.getLevel() + ", HP " + p.getMaxHP() + ", Attack " + p.getCurrentAttack() + ", Defense " + p.getCurrentDefense() + ", Special Attack " + p.getCurrentSpecialAttack() + ", Special Defense " + p.getCurrentSpecialDefense() + ", Speed " + p.getCurrentSpeed());
            }
        }
        */

        
        
        

        // Display the moves each Pokémon has learned
        /* 
        System.out.println(JoelAbra.getName() + " knows:");
        for (MoveSlot move : JoelAbra.getMoveset()) {
            System.out.println("- " + move.getMove().getMoveName());
        }
    

        System.out.println();
        System.out.println("Your team stats:");
        for (Pokemon p : trainer.getTeam()) {
            if (p != null) {
                System.out.println(p.getName() + ": Level " + p.getLevel() + ",  Max HP " + p.getMaxHP() + ", Current HP " + p.getCurrentHP() + ", Attack " + p.getCurrentAttack() + ", Defense " + p.getCurrentDefense() + ", Special Attack " + p.getCurrentSpecialAttack() + ", Special Defense " + p.getCurrentSpecialDefense() + ", Speed " + p.getCurrentSpeed());
            }
        }
        System.out.println();
        System.out.println("Opponent's team stats:");
        
        System.out.println();
        */



        



        //Iterate through Bulby's moves and calculate effectiveness against Gengar instead of hardcoded attacks
        /*for (Move move : Bulby.getMoveset()) {
            System.out.println(Bulby.getName() + " used " + move.getMoveName() + " against " + gengar.getName() + "!");
            Attack attack = new Attack();
            float damageDone = attack.calculateDamage(Bulby, gengar, move);

            int roundedDamage = (int) Math.floor(damageDone);
            
            System.out.println(move.getMoveName() + " is a " + move.getType() + " type move and " + gengar.getName() + " is a " + gengar.getTypePrimary() + "/" + gengar.getTypeSecondary() + " type Pokemon.");
            System.out.println("Damage dealt: " + damageDone);
            System.out.println("Rounded damage: " + roundedDamage);
            System.out.println();
        }*/

        /*System.out.println(Bulby.getName() + " used Thunder against " + gengar.getName() + "!");
        Attack attack = new Attack();
        float damageDone = attack.calculateDamage(Bulby, gengar, new Thunder());
        int roundedDamage = (int) Math.floor(damageDone);
        System.out.println("Damage dealt: " + roundedDamage);  */

        //scanner.close();



    }

    public static int createTrainer(String name, long discordID, String discordUsername) {
        // This method can be used to create a trainer and set up their team
        // Create a Trainer and ask for their name
        TrainerCRUD trainerCRUDSearch = new TrainerCRUD();
        Trainer trainerSearch = trainerCRUDSearch.getTrainerByDiscordId(discordID);
        
        if (trainerSearch != null) {
            System.out.println("Welcome back, " + trainerSearch.getName() + "!");
            return -1; // Return -1 to indicate that a new trainer was not created
        } else {
            System.out.println("No existing trainer found with Discord ID: " + discordID);
            System.out.println("Creating a new trainer profile for " + name + "...");
        
        
            Trainer trainer = new Trainer(name);

            TrainerCRUD trainerCRUDCreate = new TrainerCRUD();
            int trainerId = trainerCRUDCreate.createDBTrainer(discordID, discordUsername, name);
            trainer.setDBId(trainerId);

            System.out.println(trainer.getName() + ", welcome to the world of Pokemon!");

            System.out.println();
            System.out.println();
            System.out.println();

            System.out.println("You can have up to 6 Pokemon on your team. Let's start by choosing your first Pokemon!");

            return 1; // Return 1 to indicate that a new trainer was created
        }
    }


    /**
     * Present a Pokémon's eligible learnset and let the player pick a move
     * to learn.  All I/O stays here in the controller; the domain classes
     * (Pokemon, LearnsetEntry) remain I/O-free.
     */
    public static void teachMoveFromLearnset(Pokemon p) {
        Console console = System.console();
        if (console == null) {
            System.out.println("No console available. Cannot teach move.");
            return;
        }
        List<LearnsetEntry> eligible = LearnsetEntry.getEligibleMoves(p);

        if (eligible.isEmpty()) {
            System.out.println(p.getNickname() + " has no new moves to learn right now.");
            return;
        }

        System.out.println("Pick a move for " + p.getNickname() + " to learn:");
        for (int i = 0; i < eligible.size(); i++) {
            LearnsetEntry e = eligible.get(i);
            System.out.printf("  %d: %s (%s %d)%n",
                    i + 1,
                    e.getMove().getMoveName(),
                    e.getSource(), e.getParameter());
        }

        System.out.print("Choice (1-" + eligible.size() + "): ");
        int choice = Integer.parseInt(console.readLine());
        if (choice < 1 || choice > eligible.size()) {
            System.out.println("Invalid choice. No move learned.");
            return;
        }

        Move picked = eligible.get(choice - 1).getMove();

        // If the moveset isn't full, just add it directly
        if (p.addMove(picked)) {
            System.out.println(p.getNickname() + " learned " + picked.getMoveName() + "!");
            return;
        }

        // Moveset is full — ask which move to replace
        System.out.println(p.getNickname() + " already knows 4 moves.");
        System.out.println("Replace a move with " + picked.getMoveName() + "? (yes/no)");
        String response = console.readLine();
        if (!response.equalsIgnoreCase("yes")) {
            System.out.println(p.getNickname() + " did not learn " + picked.getMoveName() + ".");
            return;
        }

        System.out.println("Which move should be forgotten?");
        for (int i = 0; i < p.getMoveset().size(); i++) {
            System.out.println("  " + (i + 1) + ": " + p.getMoveset().get(i).getMove().getMoveName());
        }
        System.out.print("Choice (1-4): ");
        int slot = Integer.parseInt(console.readLine());
        if (p.replaceMove(slot - 1, picked)) {
            System.out.println(p.getNickname() + " forgot a move and learned " + picked.getMoveName() + "!");
        } else {
            System.out.println("Invalid slot. Move not learned.");
        }
    }

    
    
}
